/** Authoritative SLAYER 11v11 simulation: fixed 60 Hz, server-owned state. */
const PITCH_HALF_LENGTH=52, PITCH_HALF_WIDTH=34, GOAL_WIDTH=7.32, GOAL_HEIGHT=2.44;
const BALL_RADIUS=.11, GRAVITY=-9.81, RESTITUTION=.65, POSSESSION_RADIUS=1.2;
const MAX_SPEED=7.5, MAX_KICK_FORCE=35, INPUT_GAP=32, HISTORY_TICKS=180;
const clamp=(v,a,b)=>Math.max(a,Math.min(b,Number.isFinite(v)?v:0));
const vlen=(x,z)=>Math.hypot(x,z);

export class ServerPhysics {
 constructor(){this.ball={x:0,y:BALL_RADIUS,z:0,vx:0,vy:0,vz:0,spinX:0,spinY:0,spinZ:0,ownerId:null};this.players=new Map();this.serverTick=0;this.lastGoal=null;this.history=[];}
 addPlayer(netId,team,role="ST"){if(this.players.size>=22&&!this.players.has(netId))return false;if([...this.players.values()].filter(p=>p.team===team).length>=11&&!this.players.has(netId))return false;this.players.set(netId,{netId,team,role,x:team==="home"?-10:10,z:0,vx:0,vz:0,rotationY:team==="home"?0:Math.PI,isTackling:false,hasBall:false,lastSequence:0,suspiciousInputs:0,connected:true,lastInputAt:Date.now()});return true;}
 removePlayer(id){if(this.ball.ownerId===id)this.ball.ownerId=null;this.players.delete(id);}
 processInput(id,input={}){const p=this.players.get(id);if(!p)return false;const seq=Math.max(0,Math.floor(Number(input.sequence)||0));if(seq<=p.lastSequence||seq-p.lastSequence>INPUT_GAP){p.suspiciousInputs++;return false;}p.lastSequence=seq;p.lastInputAt=Date.now();let x=clamp(input.moveX,-1,1),z=clamp(input.moveZ,-1,1),l=vlen(x,z);if(l>1){x/=l;z/=l;}const speed=input.sprint?7:4.5;p.vx=x*speed;p.vz=z*speed;if(l>.001)p.rotationY=Math.atan2(x,z);p.isTackling=!!input.tackle;p.requestKick=!!(input.kick||input.shoot);p.requestKickPower=clamp(input.kickPower??input.power??0,0,1);return true;}
 step(dt=1/60){const d=1/60;this.serverTick++;for(const p of this.players.values()){p.x=clamp(p.x+p.vx*d,-PITCH_HALF_LENGTH,PITCH_HALF_LENGTH);p.z=clamp(p.z+p.vz*d,-PITCH_HALF_WIDTH,PITCH_HALF_WIDTH);}this.resolvePlayerCollisions();this.processKicks();this.stepBall(d);this.resolvePossession();this.saveHistory();}
 processKicks(){for(const p of this.players.values()){if(!p.requestKick)continue;p.requestKick=false;if(this.ball.ownerId!==p.netId)continue;const f=p.requestKickPower*MAX_KICK_FORCE;this.ball.ownerId=null;this.ball.vx=Math.sin(p.rotationY)*f;this.ball.vz=Math.cos(p.rotationY)*f;this.ball.vy=f*.25;this.ball.spinY=Math.min(12,f*.3);}}
 stepBall(dt){if(this.ball.ownerId!==null){const p=this.players.get(this.ball.ownerId);if(p){this.ball.x=p.x+Math.sin(p.rotationY)*.55;this.ball.z=p.z+Math.cos(p.rotationY)*.55;this.ball.y=BALL_RADIUS;this.ball.vx=p.vx;this.ball.vy=0;this.ball.vz=p.vz;return;}this.ball.ownerId=null;}this.ball.vx*=.982;this.ball.vz*=.982;this.ball.vy+=GRAVITY*dt;this.ball.vx+=this.ball.spinY*this.ball.vz*.0015*dt;this.ball.vz-=this.ball.spinY*this.ball.vx*.0015*dt;this.ball.x+=this.ball.vx*dt;this.ball.y+=this.ball.vy*dt;this.ball.z+=this.ball.vz*dt;if(this.ball.y<=BALL_RADIUS){this.ball.y=BALL_RADIUS;this.ball.vy=Math.abs(this.ball.vy)>1?-this.ball.vy*RESTITUTION:0;}this.resolvePitch();}
 resolvePitch(){if(Math.abs(this.ball.x)>PITCH_HALF_LENGTH){this.ball.x=clamp(this.ball.x,-PITCH_HALF_LENGTH,PITCH_HALF_LENGTH);this.ball.vx*=-RESTITUTION;}if(Math.abs(this.ball.z)<=PITCH_HALF_WIDTH)return;const goal=Math.abs(this.ball.x)<=GOAL_WIDTH/2&&this.ball.y<=GOAL_HEIGHT;if(goal){this.lastGoal={team:this.ball.z>0?"home":"away",tick:this.serverTick};this.resetAfterGoal();return;}this.ball.z=clamp(this.ball.z,-PITCH_HALF_WIDTH,PITCH_HALF_WIDTH);this.ball.vz*=-RESTITUTION;}
 resolvePlayerCollisions(){const a=[...this.players.values()],r=.55;for(let i=0;i<a.length;i++)for(let j=i+1;j<a.length;j++){let p=a[i],q=a[j],dx=q.x-p.x,dz=q.z-p.z,d=Math.hypot(dx,dz);if(d<=0||d>=r)continue;dx/=d;dz/=d;const push=(r-d)*.5;p.x-=dx*push;p.z-=dz*push;q.x+=dx*push;q.z+=dz*push;}}
 resolvePossession(){for(const p of this.players.values())p.hasBall=false;if(this.ball.ownerId!==null){const p=this.players.get(this.ball.ownerId);if(p)p.hasBall=true;return;}let best=null,bd=POSSESSION_RADIUS;for(const p of this.players.values()){const d=Math.hypot(this.ball.x-p.x,this.ball.z-p.z),r=POSSESSION_RADIUS+(p.isTackling?.25:0);if(d<=r&&d<bd){bd=d;best=p;}}if(best){this.ball.ownerId=best.netId;best.hasBall=true;}}
 resetAfterGoal(){this.ball={x:0,y:BALL_RADIUS,z:0,vx:0,vy:0,vz:0,spinX:0,spinY:0,spinZ:0,ownerId:null};for(const p of this.players.values())p.hasBall=false;}
 saveHistory(){this.history.push({tick:this.serverTick,players:[...this.players.values()].map(p=>({netId:p.netId,x:p.x,z:p.z,rotationY:p.rotationY}))});if(this.history.length>HISTORY_TICKS)this.history.shift();}
 getHistoricalPlayer(netId,tick){for(let i=this.history.length-1;i>=0;i--){if(this.history[i].tick<=tick)return this.history[i].players.find(p=>p.netId===netId)||null;}return null;}
}
export default ServerPhysics;
